package me.jsbn.blogapplication;
import me.jsbn.blogapplication.model.Post;
import me.jsbn.blogapplication.repository.PostRepository;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import sun.tools.jar.CommandLine;

@SpringBootApplication
@EnableJpaAuditing
@EnableAutoConfiguration
public class DemoApplication {

	@Autowired
	PostRepository postRepository;

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	public CommandLineRunner addPosts() {
		return args -> {
			postRepository.save(new Post("My First Post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu hendrerit turpis, ut aliquam quam. Mauris finibus sem ac nunc mattis, vel semper est faucibus. Donec vitae tincidunt lacus. Cras gravida sed tellus sed laoreet. Donec nunc risus, posuere eget augue ac, tempor viverra justo. Donec varius ac ipsum ut ultricies. Fusce egestas purus non porttitor vulputate."));
			postRepository.save(new Post("My Second Post", "Pellentesque auctor viverra metus, ut aliquam tortor cursus nec. Fusce ac maximus arcu. In gravida varius sodales. Donec aliquam mi ut urna pharetra viverra. Nunc convallis posuere imperdiet. Nullam ac erat sit amet libero auctor dignissim id quis lectus. Curabitur commodo blandit risus, eu ultrices lectus bibendum eu. Cras ac ultricies tellus, et efficitur velit. Phasellus maximus ligula erat, ac malesuada libero facilisis vitae. Etiam a metus faucibus, auctor elit at, laoreet ante. Nunc sit amet risus at risus semper convallis. Praesent diam nisl, rhoncus in lacus imperdiet, faucibus mollis nisl. Etiam a nulla sagittis, eleifend orci sagittis, luctus libero.\n" +
					"\n" +
					"Praesent efficitur eget justo ac pretium. Curabitur venenatis cursus ligula. Nullam vitae iaculis nulla. Quisque rhoncus felis et condimentum suscipit. Sed non diam quis odio consectetur tempor. Nullam et egestas felis. Integer nec sem luctus, rutrum ipsum id, laoreet magna. Maecenas vitae feugiat ipsum, non facilisis lacus. Aenean porttitor mauris ut ullamcorper tempus. Aenean ut orci finibus, aliquet arcu eget, molestie mi. Vestibulum diam urna, accumsan eu tincidunt id, laoreet eu risus. Mauris quis eros vitae eros volutpat accumsan at in nunc. Sed finibus vulputate dui ut hendrerit."));
			postRepository.save(new Post("My Third Post", "Nam facilisis justo ipsum, vel lacinia odio suscipit eleifend. Nunc turpis justo, tincidunt ut turpis sed, pulvinar condimentum nisl. Ut pharetra augue vitae odio finibus, at dictum ipsum mollis. Quisque ultricies lobortis pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas ut urna eget orci suscipit blandit. Quisque pretium mollis sapien non vulputate. Curabitur hendrerit dignissim hendrerit. Phasellus sit amet tortor id ligula molestie malesuada. Vestibulum blandit accumsan eros a faucibus. Vivamus mattis ante nec venenatis malesuada.\n" +
					"\n" +
					"Etiam molestie justo at lectus egestas cursus. Nullam vehicula viverra justo, nec elementum odio tempor non. Etiam eu consectetur velit, eget vestibulum augue. Curabitur facilisis, tellus et ornare consequat, lacus enim sodales tellus, eu laoreet mi urna eu ante. Integer turpis ipsum, interdum et bibendum ac, dignissim non mi. Nullam sem ligula, sollicitudin id tincidunt sit amet, mattis blandit orci. Suspendisse vulputate libero odio, ut scelerisque risus fermentum eget. Mauris in vulputate elit. Sed id ultricies magna. Duis a diam vel purus scelerisque faucibus in eu mauris. Donec vitae velit laoreet, venenatis ipsum sit amet, dignissim nulla. Maecenas orci nulla, hendrerit et fermentum molestie, porttitor vitae ipsum.\n" +
					"\n" +
					"Sed vel hendrerit metus. Nulla facilisi. Ut a nibh ac nisi molestie vulputate nec quis neque. Donec molestie pretium sagittis. Proin varius augue vel justo varius, vel tristique tellus tempor. Aliquam malesuada eget dui non convallis. Donec sodales, odio at facilisis pharetra, tellus arcu malesuada eros, ac scelerisque ex tortor sed mi. In vitae lorem a turpis congue sollicitudin non vel risus. Nunc id arcu ut nibh vulputate cursus. Donec turpis mauris, rhoncus ac congue id, vestibulum at ante. Curabitur iaculis tempor aliquam. Ut sit amet tortor velit. Duis pellentesque dignissim dui, molestie scelerisque turpis finibus vel. Aliquam sem felis, euismod quis aliquam vitae, egestas id felis. Phasellus dapibus felis eu erat cursus, in hendrerit nisi consectetur.\n" +
					"\n" +
					"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse iaculis imperdiet purus, non ornare turpis tincidunt pharetra. Maecenas eget urna in libero rhoncus aliquam. Ut enim magna, iaculis vitae mollis quis, aliquam eu arcu. Nullam vel velit orci. Phasellus tristique pharetra libero cursus gravida. Maecenas est lorem, bibendum nec augue eget, venenatis dignissim mi. Proin nec porttitor dui, nec pulvinar ante. Aliquam aliquet nisi iaculis mauris fringilla dictum.\n" +
					"\n" +
					"Suspendisse dictum metus in pulvinar fermentum. Donec sit amet sapien pellentesque, semper mauris sit amet, gravida ligula. Pellentesque euismod semper sapien vel malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas quam augue, malesuada vitae sapien non, blandit fringilla arcu. Nam ac dolor vel erat ultricies finibus. Quisque ut ante nibh. Suspendisse id molestie odio. Integer ligula est, vehicula non neque et, facilisis laoreet libero. Maecenas placerat leo vitae leo pulvinar, id venenatis enim vestibulum. Nulla condimentum ante sed porta elementum. Vestibulum fringilla mauris a turpis dapibus, non pretium urna vehicula. Duis pellentesque lacus metus, at sodales eros volutpat nec.\n" +
					"\n" +
					"Aenean porttitor augue ut sapien sollicitudin placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed iaculis pretium erat, dignissim tristique velit molestie vel. Nullam velit justo, maximus in viverra quis, condimentum eget purus. Suspendisse ut mattis lorem, vel consectetur tortor. Vestibulum non commodo odio, vel aliquam erat. Mauris porta massa a velit ullamcorper tempus. Mauris tristique et urna ut mollis. Ut eu aliquam eros. Sed ac nisi libero. Sed ante dui, tincidunt id sagittis nec, volutpat in dolor. Nulla mollis dui vitae mauris dapibus varius. Aliquam vehicula arcu vel ante lobortis, eu ultrices magna hendrerit. Quisque eu rhoncus ipsum, ut ultricies nisi. Cras ultricies magna eget mattis imperdiet.\n" +
					"\n" +
					"Curabitur in sapien vitae velit consequat auctor. Nam iaculis pulvinar enim vitae viverra. Integer vel commodo eros, eget laoreet velit. Aenean turpis erat, ullamcorper id odio sed, pharetra aliquam purus. Suspendisse vulputate tempus augue, sed dignissim arcu hendrerit at. Vestibulum volutpat nunc varius quam luctus, non lacinia odio euismod. Mauris mollis vehicula scelerisque. Aenean ut suscipit nulla, eu luctus neque. Cras ultrices metus non mauris tincidunt viverra in in quam. Curabitur sit amet congue lorem. Praesent pulvinar, arcu at commodo pulvinar, mi eros commodo enim, at euismod enim nibh a nisl. Etiam velit erat, interdum vitae ligula vel, feugiat accumsan justo. Donec eros elit, lobortis in imperdiet id, gravida vel orci. Proin sollicitudin, est et suscipit ultricies, erat urna tempor quam, non ornare ante nibh a leo.\n" +
					"\n" +
					"Praesent consequat, velit ac vestibulum accumsan, elit nulla scelerisque nisl, eu laoreet mauris eros a tortor. In hac habitasse platea dictumst. Suspendisse faucibus molestie velit vel varius. Phasellus at lectus maximus, lobortis sem et, cursus enim. Curabitur vitae nibh nibh. In a massa lobortis neque venenatis scelerisque auctor non orci. Etiam hendrerit semper suscipit. Nullam tristique dictum velit eget laoreet. Cras bibendum, massa at vehicula ultrices, justo lorem ultrices arcu, ac ornare elit sapien vel odio. Fusce felis dui, bibendum in interdum at, pulvinar in ligula. Sed ac condimentum risus. Aliquam vel interdum est, in efficitur elit. Etiam in ante suscipit lorem sodales commodo at sit amet est. Nulla quis pharetra turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\n" +
					"\n" +
					"Curabitur aliquet luctus ipsum in vehicula. Nam vel risus ac risus fermentum accumsan non quis ipsum. Nulla in urna ipsum. Nam finibus, turpis vel bibendum aliquet, metus mi lacinia ligula, sed blandit ante est quis lorem. Nam imperdiet nulla ut massa commodo, non tristique risus ultrices. Aenean ac nulla et libero hendrerit placerat nec id orci. Praesent euismod orci gravida neque molestie consequat. Ut volutpat sed dolor sit amet tincidunt. Suspendisse ligula enim, ultrices sollicitudin egestas nec, auctor vel est. Donec non euismod tortor. Fusce ornare tortor mi, sed dapibus elit congue in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus nec odio malesuada, tristique leo sit amet, lacinia risus. Vivamus turpis nulla, consequat id leo eu, volutpat fermentum massa. Etiam et mattis enim, non scelerisque magna. Suspendisse vestibulum, neque quis eleifend porttitor, erat ipsum feugiat mi, et pellentesque magna nulla sed elit.\n" +
					"\n" +
					"Duis tempor odio ut ante dictum, sed mollis urna dignissim. In hac habitasse platea dictumst. Morbi ut varius turpis. Donec aliquet leo erat. Fusce iaculis, magna eget dapibus sagittis, neque purus semper lectus, et ornare purus erat ut libero. In vehicula ex non libero lobortis dignissim. Duis quam lectus, lobortis vitae nibh volutpat, laoreet dapibus ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer non purus dapibus, suscipit ligula ac, luctus quam. Sed eget eros nisi. Duis rhoncus ante sed libero hendrerit, sit amet egestas diam porttitor. Quisque id porttitor nibh. In vel egestas dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam justo massa, consectetur pharetra orci ut, molestie consequat sem. Proin pharetra justo eu ante porttitor, id placerat nunc euismod.", "four posts"));
			postRepository.save(new Post("My Fourth Post", "In hac habitasse platea dictumst. Maecenas rhoncus lectus et neque commodo consectetur. Fusce iaculis turpis eu arcu lacinia, eu interdum sapien viverra. Donec maximus leo ac gravida cursus. Pellentesque eget commodo dolor. Proin a finibus nunc. Integer nec tortor consectetur, tristique purus vel, mollis enim. Donec tincidunt nec tellus ac pretium. Nunc id mauris tempor, vehicula diam a, sagittis metus. Ut a eros in purus fringilla interdum id non odio. Etiam vitae aliquet lacus. Sed hendrerit viverra justo quis venenatis.\n" +
					"\n", "four posts"));
			postRepository.save(new Post("My Fifth Post", "Nunc eget tempor diam. Praesent ullamcorper nibh nec nisl scelerisque euismod. Nam at tortor ullamcorper, tristique magna lobortis, varius nisl. Donec eget nibh dictum ipsum auctor scelerisque ut eu augue. Aenean dictum elit mauris, fringilla porttitor dui euismod in. Pellentesque ullamcorper dignissim risus ac imperdiet. Fusce dignissim diam nisi, venenatis fringilla ipsum aliquet ut. Praesent nulla nulla, eleifend id venenatis eget, convallis vel justo. Integer mollis ante eget cursus vehicula. Sed aliquet lacinia lectus. Nunc rhoncus dictum enim. Cras imperdiet interdum diam, ac fermentum tellus eleifend gravida. Donec sed auctor lectus.\n" +
					"\n" +
					"Ut suscipit at arcu sit amet ultrices. Donec quis bibendum felis, quis maximus sem. Morbi congue vehicula viverra. Cras vel nulla id libero fringilla fermentum. In accumsan posuere facilisis. Quisque ac eleifend ligula. Quisque tortor lacus, porttitor maximus molestie non, semper euismod mauris. Duis pharetra tortor lorem, ut scelerisque felis maximus eget. Maecenas in facilisis ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed ullamcorper magna metus.\n" +
					"\n" +
					"Mauris vel hendrerit diam. Quisque turpis sapien, fringilla nec efficitur at, tempus ut metus. Proin risus elit, dictum quis sem quis, elementum mattis est. Praesent sagittis porta sapien vitae pulvinar. Fusce consequat turpis et aliquet posuere. Etiam vel justo varius, suscipit lacus eu, consectetur ligula. Suspendisse potenti. Praesent vestibulum, turpis eu semper semper, nibh sem ultricies nunc, non ullamcorper ex nibh ut est. Fusce vulputate consectetur quam vitae tincidunt. Vestibulum diam ante, facilisis ac quam a, tincidunt ultricies quam. In hac habitasse platea dictumst.", "four posts"));
			postRepository.save(new Post("My Sixth Post", "Sed placerat odio sed est feugiat fermentum. Sed neque orci, volutpat a finibus sed, venenatis vitae diam. Nullam sagittis tincidunt leo, vitae euismod magna tempus et. Etiam vitae tincidunt risus, vel facilisis arcu. Vivamus ut nibh quis nisi dapibus aliquet nec sit amet orci. Donec eleifend vel mauris eget bibendum. Cras lectus lectus, elementum non mollis et, feugiat eget sem. Sed vitae ornare ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent ut nisi sit amet augue aliquam pretium ut ac nisi. Duis ante ante, rhoncus sit amet ipsum ut, aliquam fermentum magna. Nunc lobortis enim et diam eleifend, a efficitur tortor pellentesque.", "two posts", "three posts"));
			postRepository.save(new Post("My Seventh Post", "Aenean arcu leo, ultricies eu malesuada vel, pharetra at dui. Curabitur dictum enim nisl. Ut tincidunt ligula ut mi finibus, at lacinia ipsum dictum. Nam sed porttitor est. Etiam dictum odio non justo sagittis ullamcorper. Donec eu enim at elit venenatis gravida. Suspendisse semper tellus at lectus congue, id placerat mauris tincidunt. Maecenas gravida porttitor velit sed dapibus. Nulla iaculis, lectus nec tristique ornare, erat felis sollicitudin leo, non finibus mauris tortor id urna. Etiam eget mi sed lorem molestie interdum non quis orci."));
			postRepository.save(new Post("My Eighth Post", "Quisque in nisl porttitor libero aliquam scelerisque faucibus sit amet eros. Vivamus condimentum blandit sem ut pretium. Aenean at ipsum lacinia, commodo lectus ut, efficitur leo. Proin nec augue dolor. Sed tempus finibus purus nec ultricies. Quisque vitae mauris sollicitudin, tempor elit eu, pulvinar orci. Integer egestas dapibus auctor. Etiam hendrerit ex sed dictum pulvinar. Donec faucibus, tellus id lobortis ultrices, arcu massa vestibulum nibh, id suscipit augue elit sed magna. Phasellus sed dictum purus. Nunc sit amet arcu blandit, congue risus a, luctus velit.", "two posts", "three posts", "one post"));
			postRepository.save(new Post("My Ninth Post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu hendrerit turpis, ut aliquam quam. Mauris finibus sem ac nunc mattis, vel semper est faucibus. Donec vitae tincidunt lacus. Cras gravida sed tellus sed laoreet. Donec nunc risus, posuere eget augue ac, tempor viverra justo. Donec varius ac ipsum ut ultricies. Fusce egestas purus non porttitor vulputate.", "three posts", "four posts"));
		};
	}
}
